// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {hub} from '../models';

export function GetCommandLineTool(arg1:number):Promise<hub.RespGetCommandLineTool>;

export function GetDirs():Promise<hub.Dirs>;

export function GetHTTPTool(arg1:number):Promise<hub.RespGetHTTPTool>;

export function GetSettings(arg1:Array<string>):Promise<hub.RespGetSettings>;

export function GetTool(arg1:number):Promise<hub.RespGetTool>;

export function GetToolList():Promise<hub.RespGetToolList>;

export function GetToolTestcaseList(arg1:string):Promise<hub.RespGetToolTestcaseList>;

export function SaveSetting(arg1:string,arg2:string):Promise<hub.RespSaveSetting>;
