// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCommandLineTool(arg1) {
  return window['go']['hub']['Model']['GetCommandLineTool'](arg1);
}

export function GetDirs() {
  return window['go']['hub']['Model']['GetDirs']();
}

export function GetHTTPTool(arg1) {
  return window['go']['hub']['Model']['GetHTTPTool'](arg1);
}

export function GetSettings(arg1) {
  return window['go']['hub']['Model']['GetSettings'](arg1);
}

export function GetTool(arg1) {
  return window['go']['hub']['Model']['GetTool'](arg1);
}

export function GetToolList() {
  return window['go']['hub']['Model']['GetToolList']();
}

export function GetToolTestcaseList(arg1) {
  return window['go']['hub']['Model']['GetToolTestcaseList'](arg1);
}

export function SaveSetting(arg1, arg2) {
  return window['go']['hub']['Model']['SaveSetting'](arg1, arg2);
}
